/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { WedInvPaymentService } from "../wedInvPayment.service";
import { WedInvPaymentCreateInput } from "./WedInvPaymentCreateInput";
import { WedInvPaymentWhereInput } from "./WedInvPaymentWhereInput";
import { WedInvPaymentWhereUniqueInput } from "./WedInvPaymentWhereUniqueInput";
import { WedInvPaymentFindManyArgs } from "./WedInvPaymentFindManyArgs";
import { WedInvPaymentUpdateInput } from "./WedInvPaymentUpdateInput";
import { WedInvPayment } from "./WedInvPayment";

export class WedInvPaymentGrpcControllerBase {
  constructor(protected readonly service: WedInvPaymentService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WedInvPayment })
  @GrpcMethod("WedInvPaymentService", "createWedInvPayment")
  async createWedInvPayment(
    @common.Body() data: WedInvPaymentCreateInput
  ): Promise<WedInvPayment> {
    return await this.service.createWedInvPayment({
      data: {
        ...data,

        dtPaymentMethod: data.dtPaymentMethod
          ? {
              connect: data.dtPaymentMethod,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        wedInv: data.wedInv
          ? {
              connect: data.wedInv,
            }
          : undefined,
      },
      select: {
        accountName: true,
        accountNo: true,
        amount: true,
        createdAt: true,

        dtPaymentMethod: {
          select: {
            id: true,
          },
        },

        evidence: true,
        id: true,
        noRef: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [WedInvPayment] })
  @ApiNestedQuery(WedInvPaymentFindManyArgs)
  @GrpcMethod("WedInvPaymentService", "wedInvPayments")
  async wedInvPayments(
    @common.Req() request: Request
  ): Promise<WedInvPayment[]> {
    const args = plainToClass(WedInvPaymentFindManyArgs, request.query);
    return this.service.wedInvPayments({
      ...args,
      select: {
        accountName: true,
        accountNo: true,
        amount: true,
        createdAt: true,

        dtPaymentMethod: {
          select: {
            id: true,
          },
        },

        evidence: true,
        id: true,
        noRef: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WedInvPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvPaymentService", "wedInvPayment")
  async wedInvPayment(
    @common.Param() params: WedInvPaymentWhereUniqueInput
  ): Promise<WedInvPayment | null> {
    const result = await this.service.wedInvPayment({
      where: params,
      select: {
        accountName: true,
        accountNo: true,
        amount: true,
        createdAt: true,

        dtPaymentMethod: {
          select: {
            id: true,
          },
        },

        evidence: true,
        id: true,
        noRef: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WedInvPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvPaymentService", "updateWedInvPayment")
  async updateWedInvPayment(
    @common.Param() params: WedInvPaymentWhereUniqueInput,
    @common.Body() data: WedInvPaymentUpdateInput
  ): Promise<WedInvPayment | null> {
    try {
      return await this.service.updateWedInvPayment({
        where: params,
        data: {
          ...data,

          dtPaymentMethod: data.dtPaymentMethod
            ? {
                connect: data.dtPaymentMethod,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          wedInv: data.wedInv
            ? {
                connect: data.wedInv,
              }
            : undefined,
        },
        select: {
          accountName: true,
          accountNo: true,
          amount: true,
          createdAt: true,

          dtPaymentMethod: {
            select: {
              id: true,
            },
          },

          evidence: true,
          id: true,
          noRef: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WedInvPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvPaymentService", "deleteWedInvPayment")
  async deleteWedInvPayment(
    @common.Param() params: WedInvPaymentWhereUniqueInput
  ): Promise<WedInvPayment | null> {
    try {
      return await this.service.deleteWedInvPayment({
        where: params,
        select: {
          accountName: true,
          accountNo: true,
          amount: true,
          createdAt: true,

          dtPaymentMethod: {
            select: {
              id: true,
            },
          },

          evidence: true,
          id: true,
          noRef: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
