/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  WedInvGift as PrismaWedInvGift,
  DtGift as PrismaDtGift,
  WedInv as PrismaWedInv,
} from "@prisma/client";

export class WedInvGiftServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.WedInvGiftCountArgs, "select">
  ): Promise<number> {
    return this.prisma.wedInvGift.count(args);
  }

  async wedInvGifts<T extends Prisma.WedInvGiftFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGiftFindManyArgs>
  ): Promise<PrismaWedInvGift[]> {
    return this.prisma.wedInvGift.findMany<Prisma.WedInvGiftFindManyArgs>(args);
  }
  async wedInvGift<T extends Prisma.WedInvGiftFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGiftFindUniqueArgs>
  ): Promise<PrismaWedInvGift | null> {
    return this.prisma.wedInvGift.findUnique(args);
  }
  async createWedInvGift<T extends Prisma.WedInvGiftCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGiftCreateArgs>
  ): Promise<PrismaWedInvGift> {
    return this.prisma.wedInvGift.create<T>(args);
  }
  async updateWedInvGift<T extends Prisma.WedInvGiftUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGiftUpdateArgs>
  ): Promise<PrismaWedInvGift> {
    return this.prisma.wedInvGift.update<T>(args);
  }
  async deleteWedInvGift<T extends Prisma.WedInvGiftDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvGiftDeleteArgs>
  ): Promise<PrismaWedInvGift> {
    return this.prisma.wedInvGift.delete(args);
  }

  async getDtGiftId(parentId: string): Promise<PrismaDtGift | null> {
    return this.prisma.wedInvGift
      .findUnique({
        where: { id: parentId },
      })
      .dtGiftId();
  }

  async getWedInvId(parentId: string): Promise<PrismaWedInv | null> {
    return this.prisma.wedInvGift
      .findUnique({
        where: { id: parentId },
      })
      .wedInvId();
  }
}
