/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WedInvGiftService } from "../wedInvGift.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WedInvGiftCreateInput } from "./WedInvGiftCreateInput";
import { WedInvGift } from "./WedInvGift";
import { WedInvGiftFindManyArgs } from "./WedInvGiftFindManyArgs";
import { WedInvGiftWhereUniqueInput } from "./WedInvGiftWhereUniqueInput";
import { WedInvGiftUpdateInput } from "./WedInvGiftUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WedInvGiftControllerBase {
  constructor(
    protected readonly service: WedInvGiftService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WedInvGift })
  @nestAccessControl.UseRoles({
    resource: "WedInvGift",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWedInvGift(
    @common.Body() data: WedInvGiftCreateInput
  ): Promise<WedInvGift> {
    return await this.service.createWedInvGift({
      data: {
        ...data,

        dtGiftId: data.dtGiftId
          ? {
              connect: data.dtGiftId,
            }
          : undefined,

        wedInvId: data.wedInvId
          ? {
              connect: data.wedInvId,
            }
          : undefined,
      },
      select: {
        accountName: true,
        accountNo: true,
        accountPhoto: true,
        createdAt: true,
        details: true,

        dtGiftId: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WedInvGift] })
  @ApiNestedQuery(WedInvGiftFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WedInvGift",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvGifts(@common.Req() request: Request): Promise<WedInvGift[]> {
    const args = plainToClass(WedInvGiftFindManyArgs, request.query);
    return this.service.wedInvGifts({
      ...args,
      select: {
        accountName: true,
        accountNo: true,
        accountPhoto: true,
        createdAt: true,
        details: true,

        dtGiftId: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WedInvGift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvGift",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvGift(
    @common.Param() params: WedInvGiftWhereUniqueInput
  ): Promise<WedInvGift | null> {
    const result = await this.service.wedInvGift({
      where: params,
      select: {
        accountName: true,
        accountNo: true,
        accountPhoto: true,
        createdAt: true,
        details: true,

        dtGiftId: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WedInvGift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvGift",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWedInvGift(
    @common.Param() params: WedInvGiftWhereUniqueInput,
    @common.Body() data: WedInvGiftUpdateInput
  ): Promise<WedInvGift | null> {
    try {
      return await this.service.updateWedInvGift({
        where: params,
        data: {
          ...data,

          dtGiftId: data.dtGiftId
            ? {
                connect: data.dtGiftId,
              }
            : undefined,

          wedInvId: data.wedInvId
            ? {
                connect: data.wedInvId,
              }
            : undefined,
        },
        select: {
          accountName: true,
          accountNo: true,
          accountPhoto: true,
          createdAt: true,
          details: true,

          dtGiftId: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,

          wedInvId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WedInvGift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvGift",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWedInvGift(
    @common.Param() params: WedInvGiftWhereUniqueInput
  ): Promise<WedInvGift | null> {
    try {
      return await this.service.deleteWedInvGift({
        where: params,
        select: {
          accountName: true,
          accountNo: true,
          accountPhoto: true,
          createdAt: true,
          details: true,

          dtGiftId: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,

          wedInvId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
