/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { WedInvGalleryService } from "../wedInvGallery.service";
import { WedInvGalleryCreateInput } from "./WedInvGalleryCreateInput";
import { WedInvGalleryWhereInput } from "./WedInvGalleryWhereInput";
import { WedInvGalleryWhereUniqueInput } from "./WedInvGalleryWhereUniqueInput";
import { WedInvGalleryFindManyArgs } from "./WedInvGalleryFindManyArgs";
import { WedInvGalleryUpdateInput } from "./WedInvGalleryUpdateInput";
import { WedInvGallery } from "./WedInvGallery";

export class WedInvGalleryGrpcControllerBase {
  constructor(protected readonly service: WedInvGalleryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WedInvGallery })
  @GrpcMethod("WedInvGalleryService", "createWedInvGallery")
  async createWedInvGallery(
    @common.Body() data: WedInvGalleryCreateInput
  ): Promise<WedInvGallery> {
    return await this.service.createWedInvGallery({
      data: {
        ...data,

        wedInv: data.wedInv
          ? {
              connect: data.wedInv,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        name: true,
        photo: true,
        updatedAt: true,

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [WedInvGallery] })
  @ApiNestedQuery(WedInvGalleryFindManyArgs)
  @GrpcMethod("WedInvGalleryService", "wedInvGalleries")
  async wedInvGalleries(
    @common.Req() request: Request
  ): Promise<WedInvGallery[]> {
    const args = plainToClass(WedInvGalleryFindManyArgs, request.query);
    return this.service.wedInvGalleries({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        photo: true,
        updatedAt: true,

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WedInvGallery })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvGalleryService", "wedInvGallery")
  async wedInvGallery(
    @common.Param() params: WedInvGalleryWhereUniqueInput
  ): Promise<WedInvGallery | null> {
    const result = await this.service.wedInvGallery({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        photo: true,
        updatedAt: true,

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WedInvGallery })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvGalleryService", "updateWedInvGallery")
  async updateWedInvGallery(
    @common.Param() params: WedInvGalleryWhereUniqueInput,
    @common.Body() data: WedInvGalleryUpdateInput
  ): Promise<WedInvGallery | null> {
    try {
      return await this.service.updateWedInvGallery({
        where: params,
        data: {
          ...data,

          wedInv: data.wedInv
            ? {
                connect: data.wedInv,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          name: true,
          photo: true,
          updatedAt: true,

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WedInvGallery })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvGalleryService", "deleteWedInvGallery")
  async deleteWedInvGallery(
    @common.Param() params: WedInvGalleryWhereUniqueInput
  ): Promise<WedInvGallery | null> {
    try {
      return await this.service.deleteWedInvGallery({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          photo: true,
          updatedAt: true,

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
