/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WedInvCommentService } from "../wedInvComment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WedInvCommentCreateInput } from "./WedInvCommentCreateInput";
import { WedInvComment } from "./WedInvComment";
import { WedInvCommentFindManyArgs } from "./WedInvCommentFindManyArgs";
import { WedInvCommentWhereUniqueInput } from "./WedInvCommentWhereUniqueInput";
import { WedInvCommentUpdateInput } from "./WedInvCommentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WedInvCommentControllerBase {
  constructor(
    protected readonly service: WedInvCommentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WedInvComment })
  @nestAccessControl.UseRoles({
    resource: "WedInvComment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWedInvComment(
    @common.Body() data: WedInvCommentCreateInput
  ): Promise<WedInvComment> {
    return await this.service.createWedInvComment({
      data: {
        ...data,

        wedInvId: data.wedInvId
          ? {
              connect: data.wedInvId,
            }
          : undefined,

        wedInvShareId: data.wedInvShareId
          ? {
              connect: data.wedInvShareId,
            }
          : undefined,
      },
      select: {
        comment: true,
        confirmation: true,
        createdAt: true,
        id: true,
        moment: true,
        name: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },

        wedInvShareId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WedInvComment] })
  @ApiNestedQuery(WedInvCommentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WedInvComment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvComments(
    @common.Req() request: Request
  ): Promise<WedInvComment[]> {
    const args = plainToClass(WedInvCommentFindManyArgs, request.query);
    return this.service.wedInvComments({
      ...args,
      select: {
        comment: true,
        confirmation: true,
        createdAt: true,
        id: true,
        moment: true,
        name: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },

        wedInvShareId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WedInvComment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvComment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvComment(
    @common.Param() params: WedInvCommentWhereUniqueInput
  ): Promise<WedInvComment | null> {
    const result = await this.service.wedInvComment({
      where: params,
      select: {
        comment: true,
        confirmation: true,
        createdAt: true,
        id: true,
        moment: true,
        name: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },

        wedInvShareId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WedInvComment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvComment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWedInvComment(
    @common.Param() params: WedInvCommentWhereUniqueInput,
    @common.Body() data: WedInvCommentUpdateInput
  ): Promise<WedInvComment | null> {
    try {
      return await this.service.updateWedInvComment({
        where: params,
        data: {
          ...data,

          wedInvId: data.wedInvId
            ? {
                connect: data.wedInvId,
              }
            : undefined,

          wedInvShareId: data.wedInvShareId
            ? {
                connect: data.wedInvShareId,
              }
            : undefined,
        },
        select: {
          comment: true,
          confirmation: true,
          createdAt: true,
          id: true,
          moment: true,
          name: true,
          updatedAt: true,

          wedInvId: {
            select: {
              id: true,
            },
          },

          wedInvShareId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WedInvComment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvComment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWedInvComment(
    @common.Param() params: WedInvCommentWhereUniqueInput
  ): Promise<WedInvComment | null> {
    try {
      return await this.service.deleteWedInvComment({
        where: params,
        select: {
          comment: true,
          confirmation: true,
          createdAt: true,
          id: true,
          moment: true,
          name: true,
          updatedAt: true,

          wedInvId: {
            select: {
              id: true,
            },
          },

          wedInvShareId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
