/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { WedInvVideoService } from "../wedInvVideo.service";
import { WedInvVideoCreateInput } from "./WedInvVideoCreateInput";
import { WedInvVideoWhereInput } from "./WedInvVideoWhereInput";
import { WedInvVideoWhereUniqueInput } from "./WedInvVideoWhereUniqueInput";
import { WedInvVideoFindManyArgs } from "./WedInvVideoFindManyArgs";
import { WedInvVideoUpdateInput } from "./WedInvVideoUpdateInput";
import { WedInvVideo } from "./WedInvVideo";

export class WedInvVideoGrpcControllerBase {
  constructor(protected readonly service: WedInvVideoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WedInvVideo })
  @GrpcMethod("WedInvVideoService", "createWedInvVideo")
  async createWedInvVideo(
    @common.Body() data: WedInvVideoCreateInput
  ): Promise<WedInvVideo> {
    return await this.service.createWedInvVideo({
      data: {
        ...data,

        wedInv: data.wedInv
          ? {
              connect: data.wedInv,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
        video: true,

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [WedInvVideo] })
  @ApiNestedQuery(WedInvVideoFindManyArgs)
  @GrpcMethod("WedInvVideoService", "wedInvVideos")
  async wedInvVideos(@common.Req() request: Request): Promise<WedInvVideo[]> {
    const args = plainToClass(WedInvVideoFindManyArgs, request.query);
    return this.service.wedInvVideos({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
        video: true,

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WedInvVideo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvVideoService", "wedInvVideo")
  async wedInvVideo(
    @common.Param() params: WedInvVideoWhereUniqueInput
  ): Promise<WedInvVideo | null> {
    const result = await this.service.wedInvVideo({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
        video: true,

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WedInvVideo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvVideoService", "updateWedInvVideo")
  async updateWedInvVideo(
    @common.Param() params: WedInvVideoWhereUniqueInput,
    @common.Body() data: WedInvVideoUpdateInput
  ): Promise<WedInvVideo | null> {
    try {
      return await this.service.updateWedInvVideo({
        where: params,
        data: {
          ...data,

          wedInv: data.wedInv
            ? {
                connect: data.wedInv,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
          video: true,

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WedInvVideo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("WedInvVideoService", "deleteWedInvVideo")
  async deleteWedInvVideo(
    @common.Param() params: WedInvVideoWhereUniqueInput
  ): Promise<WedInvVideo | null> {
    try {
      return await this.service.deleteWedInvVideo({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
          video: true,

          wedInv: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
