/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  WedInvStory as PrismaWedInvStory,
  WedInv as PrismaWedInv,
} from "@prisma/client";

export class WedInvStoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.WedInvStoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.wedInvStory.count(args);
  }

  async wedInvStories<T extends Prisma.WedInvStoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvStoryFindManyArgs>
  ): Promise<PrismaWedInvStory[]> {
    return this.prisma.wedInvStory.findMany<Prisma.WedInvStoryFindManyArgs>(
      args
    );
  }
  async wedInvStory<T extends Prisma.WedInvStoryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvStoryFindUniqueArgs>
  ): Promise<PrismaWedInvStory | null> {
    return this.prisma.wedInvStory.findUnique(args);
  }
  async createWedInvStory<T extends Prisma.WedInvStoryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvStoryCreateArgs>
  ): Promise<PrismaWedInvStory> {
    return this.prisma.wedInvStory.create<T>(args);
  }
  async updateWedInvStory<T extends Prisma.WedInvStoryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvStoryUpdateArgs>
  ): Promise<PrismaWedInvStory> {
    return this.prisma.wedInvStory.update<T>(args);
  }
  async deleteWedInvStory<T extends Prisma.WedInvStoryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.WedInvStoryDeleteArgs>
  ): Promise<PrismaWedInvStory> {
    return this.prisma.wedInvStory.delete(args);
  }

  async getWedInv(parentId: string): Promise<PrismaWedInv | null> {
    return this.prisma.wedInvStory
      .findUnique({
        where: { id: parentId },
      })
      .wedInv();
  }
}
