/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GrpcMethod } from "@nestjs/microservices";
import { DtGiftService } from "../dtGift.service";
import { DtGiftCreateInput } from "./DtGiftCreateInput";
import { DtGiftWhereInput } from "./DtGiftWhereInput";
import { DtGiftWhereUniqueInput } from "./DtGiftWhereUniqueInput";
import { DtGiftFindManyArgs } from "./DtGiftFindManyArgs";
import { DtGiftUpdateInput } from "./DtGiftUpdateInput";
import { DtGift } from "./DtGift";
import { WedInvGiftFindManyArgs } from "../../wedInvGift/base/WedInvGiftFindManyArgs";
import { WedInvGift } from "../../wedInvGift/base/WedInvGift";
import { WedInvGiftWhereUniqueInput } from "../../wedInvGift/base/WedInvGiftWhereUniqueInput";

export class DtGiftGrpcControllerBase {
  constructor(protected readonly service: DtGiftService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DtGift })
  @GrpcMethod("DtGiftService", "createDtGift")
  async createDtGift(@common.Body() data: DtGiftCreateInput): Promise<DtGift> {
    return await this.service.createDtGift({
      data: data,
      select: {
        createdAt: true,
        giftType: true,
        icon: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DtGift] })
  @ApiNestedQuery(DtGiftFindManyArgs)
  @GrpcMethod("DtGiftService", "dtGifts")
  async dtGifts(@common.Req() request: Request): Promise<DtGift[]> {
    const args = plainToClass(DtGiftFindManyArgs, request.query);
    return this.service.dtGifts({
      ...args,
      select: {
        createdAt: true,
        giftType: true,
        icon: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DtGift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DtGiftService", "dtGift")
  async dtGift(
    @common.Param() params: DtGiftWhereUniqueInput
  ): Promise<DtGift | null> {
    const result = await this.service.dtGift({
      where: params,
      select: {
        createdAt: true,
        giftType: true,
        icon: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DtGift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DtGiftService", "updateDtGift")
  async updateDtGift(
    @common.Param() params: DtGiftWhereUniqueInput,
    @common.Body() data: DtGiftUpdateInput
  ): Promise<DtGift | null> {
    try {
      return await this.service.updateDtGift({
        where: params,
        data: data,
        select: {
          createdAt: true,
          giftType: true,
          icon: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DtGift })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @GrpcMethod("DtGiftService", "deleteDtGift")
  async deleteDtGift(
    @common.Param() params: DtGiftWhereUniqueInput
  ): Promise<DtGift | null> {
    try {
      return await this.service.deleteDtGift({
        where: params,
        select: {
          createdAt: true,
          giftType: true,
          icon: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/wedInvGifts")
  @ApiNestedQuery(WedInvGiftFindManyArgs)
  @GrpcMethod("DtGiftService", "findManyWedInvGifts")
  async findManyWedInvGifts(
    @common.Req() request: Request,
    @common.Param() params: DtGiftWhereUniqueInput
  ): Promise<WedInvGift[]> {
    const query = plainToClass(WedInvGiftFindManyArgs, request.query);
    const results = await this.service.findWedInvGifts(params.id, {
      ...query,
      select: {
        accountName: true,
        accountNo: true,
        accountPhoto: true,
        createdAt: true,
        details: true,

        dtGift: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,

        wedInv: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/wedInvGifts")
  @GrpcMethod("DtGiftService", "connectWedInvGifts")
  async connectWedInvGifts(
    @common.Param() params: DtGiftWhereUniqueInput,
    @common.Body() body: WedInvGiftWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wedInvGifts: {
        connect: body,
      },
    };
    await this.service.updateDtGift({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/wedInvGifts")
  @GrpcMethod("DtGiftService", "updateWedInvGifts")
  async updateWedInvGifts(
    @common.Param() params: DtGiftWhereUniqueInput,
    @common.Body() body: WedInvGiftWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wedInvGifts: {
        set: body,
      },
    };
    await this.service.updateDtGift({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/wedInvGifts")
  @GrpcMethod("DtGiftService", "disconnectWedInvGifts")
  async disconnectWedInvGifts(
    @common.Param() params: DtGiftWhereUniqueInput,
    @common.Body() body: WedInvGiftWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wedInvGifts: {
        disconnect: body,
      },
    };
    await this.service.updateDtGift({
      where: params,
      data,
      select: { id: true },
    });
  }
}
