/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WedInvWeddingService } from "../wedInvWedding.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WedInvWeddingCreateInput } from "./WedInvWeddingCreateInput";
import { WedInvWedding } from "./WedInvWedding";
import { WedInvWeddingFindManyArgs } from "./WedInvWeddingFindManyArgs";
import { WedInvWeddingWhereUniqueInput } from "./WedInvWeddingWhereUniqueInput";
import { WedInvWeddingUpdateInput } from "./WedInvWeddingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WedInvWeddingControllerBase {
  constructor(
    protected readonly service: WedInvWeddingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WedInvWedding })
  @nestAccessControl.UseRoles({
    resource: "WedInvWedding",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWedInvWedding(
    @common.Body() data: WedInvWeddingCreateInput
  ): Promise<WedInvWedding> {
    return await this.service.createWedInvWedding({
      data: {
        ...data,

        wedInvId: data.wedInvId
          ? {
              connect: data.wedInvId,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        father: true,
        gender: true,
        id: true,
        mother: true,
        name: true,
        photo: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WedInvWedding] })
  @ApiNestedQuery(WedInvWeddingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WedInvWedding",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvWeddings(
    @common.Req() request: Request
  ): Promise<WedInvWedding[]> {
    const args = plainToClass(WedInvWeddingFindManyArgs, request.query);
    return this.service.wedInvWeddings({
      ...args,
      select: {
        createdAt: true,
        father: true,
        gender: true,
        id: true,
        mother: true,
        name: true,
        photo: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WedInvWedding })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvWedding",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wedInvWedding(
    @common.Param() params: WedInvWeddingWhereUniqueInput
  ): Promise<WedInvWedding | null> {
    const result = await this.service.wedInvWedding({
      where: params,
      select: {
        createdAt: true,
        father: true,
        gender: true,
        id: true,
        mother: true,
        name: true,
        photo: true,
        updatedAt: true,

        wedInvId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WedInvWedding })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvWedding",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWedInvWedding(
    @common.Param() params: WedInvWeddingWhereUniqueInput,
    @common.Body() data: WedInvWeddingUpdateInput
  ): Promise<WedInvWedding | null> {
    try {
      return await this.service.updateWedInvWedding({
        where: params,
        data: {
          ...data,

          wedInvId: data.wedInvId
            ? {
                connect: data.wedInvId,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          father: true,
          gender: true,
          id: true,
          mother: true,
          name: true,
          photo: true,
          updatedAt: true,

          wedInvId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WedInvWedding })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WedInvWedding",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWedInvWedding(
    @common.Param() params: WedInvWeddingWhereUniqueInput
  ): Promise<WedInvWedding | null> {
    try {
      return await this.service.deleteWedInvWedding({
        where: params,
        select: {
          createdAt: true,
          father: true,
          gender: true,
          id: true,
          mother: true,
          name: true,
          photo: true,
          updatedAt: true,

          wedInvId: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
